### ISSUE TITLE
Cannot Deploy - Type error: This expression is not callable.

### ISSUE THREAD

**Issue by kobykotiv** [vercel/platforms#135]
I checked Middleware #132 , I'm not sure how or why `Type 'typeof import("/vercel/path0/node_modules/unist-util-visit/index")' has no call signatures.` 

I'm very stuck and confused.

### Log

```
[23:06:36.129] Cloning github.com/kobykotiv/platforms (Branch: main, Commit: 7cd0f08)
[23:06:36.466] Cloning completed: 336.976ms
[23:06:37.341] Looking up build cache...
[23:06:44.510] Build cache downloaded [138.84 MB]: 6781.551ms
[23:06:44.817] Running "vercel build"
[23:06:45.467] Vercel CLI 27.3.2
[23:06:45.895] Warning: Detected "engines": { "node": ">=14.0.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[23:06:45.911] Installing dependencies...
[23:06:51.576] 
[23:06:51.577] added 62 packages, removed 143 packages, and changed 65 packages in 5s
[23:06:51.577] 
[23:06:51.577] 176 packages are looking for funding
[23:06:51.577]   run `npm fund` for details
[23:06:51.594] Detected Next.js version: 12.2.2
[23:06:51.600] Detected `package-lock.json` generated by npm 7+...
[23:06:51.600] Running "npm run build"
[23:06:51.980] 
[23:06:51.980] > prebuild
[23:06:51.980] > prisma generate
[23:06:51.982] 
[23:06:52.616] Prisma schema loaded from prisma/schema.prisma
[23:06:53.607] 
[23:06:53.607] ✔ Generated Prisma Client (3.8.1 | library) to ./node_modules/@prisma/client in 225ms
[23:06:53.607] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[23:06:53.608] ```
[23:06:53.608] import { PrismaClient } from '@prisma/client'
[23:06:53.610] const prisma = new PrismaClient()
[23:06:53.611] ```
[23:06:53.720] 
[23:06:53.721] > build
[23:06:53.721] > next build
[23:06:53.721] 
[23:06:54.374] info  - Linting and checking validity of types...
[23:07:04.051] Failed to compile.
[23:07:04.051] 
[23:07:04.052] ./lib/remark-plugins.tsx:35:7
[23:07:04.052] Type error: This expression is not callable.
[23:07:04.052]   Type 'typeof import("/vercel/path0/node_modules/unist-util-visit/index")' has no call signatures.
[23:07:04.052] 
[23:07:04.052] [0m [90m 33 | [39m      [36mconst[39m nodesToChange [33m=[39m [36mnew[39m [33mArray[39m[33m<[39m[33mNodesToChange[39m[33m>[39m()[33m;[39m[0m
[23:07:04.053] [0m [90m 34 | [39m[0m
[23:07:04.053] [0m[31m[1m>[22m[39m[90m 35 | [39m      visit(tree[33m,[39m [32m"text"[39m[33m,[39m (node[33m:[39m any) [33m=>[39m {[0m
[23:07:04.053] [0m [90m    | [39m      [31m[1m^[22m[39m[0m
[23:07:04.053] [0m [90m 36 | [39m        [36mif[39m ([0m
[23:07:04.053] [0m [90m 37 | [39m          node[33m.[39mvalue[33m.[39mmatch([0m
[23:07:04.053] [0m [90m 38 | [39m            [35m/https?:\/\/twitter\.com\/(?:#!\/)?(\w+)\/status(?:es)?\/(\d+)([^\?])(\?.*)?/g[39m[0m
[23:07:04.081] 
[23:07:04.081] > Build error occurred
[23:07:04.085] Error: Call retries were exceeded
[23:07:04.085]     at ChildProcessWorker.initialize (/vercel/path0/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
[23:07:04.085]     at ChildProcessWorker._onExit (/vercel/path0/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
[23:07:04.086]     at ChildProcess.emit (node:events:527:28)
[23:07:04.086]     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
[23:07:04.086]   type: 'WorkerError'
[23:07:04.086] }
[23:07:04.201] Error: Command "npm run build" exited with 1
```

**Comment by steven-tey** [comment]
Seems like something wrong with `unist-util-visit/index` – what's your version for that in `package.json`?

**Comment by ayoungh** [comment]
I had the same issue after updating packages today and I did the following to fix this: `import {visit} from "unist-util-visit";`

**Comment by steven-tey** [comment]
Oh interesting, seems like `visit` was changed to a named export in 3.0.0: https://github.com/syntax-tree/unist-util-visit/releases/tag/3.0.0

Upgraded & updated the syntax with this PR: https://github.com/vercel/platforms/pull/143 :)

Thanks again for the headsup
