### ISSUE TITLE
This Edge Function has crashed.

### ISSUE THREAD

**Issue by Sense** [vercel/platforms#157]
Hello 👋, I just cloned this template and deployed it to vercel.

Navigating to the main domain is showing off:

**This Edge Function** has crashed.
**Your connection** is working correctly.
**Vercel** is working correctly.

```
500: INTERNAL_SERVER_ERROR
Code: EDGE_FUNCTION_INVOCATION_FAILED
```

Here is my `middleware.ts`:

```
import { NextRequest, NextResponse } from 'next/server';

export const config = {
  matcher: [
    /*
     * Match all paths except for:
     * 1. /api routes
     * 2. /_next (Next.js internals)
     * 3. /fonts (inside /public)
     * 4. /examples (inside /public)
     * 5. all root files inside /public (e.g. /favicon.ico)
     */
    '/((?!api|_next|fonts|examples|[\\w-]+\\.\\w+).*)',
  ],
};

export default function middleware(req: NextRequest) {
  const url = req.nextUrl;

  const hostname = req.headers.get('host') as string;
  const domain = hostname?.split('.').slice(1).join('.');

  /*  You have to replace ".store-front.local" with your own domain if you deploy this example under your domain.
      You can also use wildcard subdomains on .vercel.app links that are associated with your Vercel team slug
      in this case, our team slug is "platformize", thus *.platformize.vercel.app works. Do note that you'll
      still need to add "*.platformize.vercel.app" as a wildcard domain on your Vercel dashboard. */
  const currentHost =
    process.env.NODE_ENV === 'production' && process.env.VERCEL === '1'
      ? hostname
          .replace(`.${domain}`, '')
          .replace(`.platformize.vercel.app`, '')
      : hostname.replace(`.${domain}`, '');
  // rewrites for app pages
  if (currentHost == 'app') {
    if (
      url.pathname === '/login' &&
      (req.cookies.get('next-auth.session-token') ||
        req.cookies.get('__Secure-next-auth.session-token'))
    ) {
      url.pathname = '/';
      return NextResponse.redirect(url);
    }

    url.pathname = `/app${url.pathname}`;
    return NextResponse.rewrite(url);
  }

  // rewrite root application to `/home` folder
  if (hostname === domain) {
    url.pathname = `/home${url.pathname}`;
    return NextResponse.rewrite(url);
  }

  // rewrite everything else to `/_sites/[site] dynamic route
  url.pathname = `/_sites/${currentHost}${url.pathname}`;
  return NextResponse.rewrite(url);
}

```

Logs on Vercel are showing:

```
ReferenceError: __dirname is not defined
    at node_modules/next/dist/compiled/ua-parser-js/ua-parser.js:10:16756
    at node_modules/next/dist/compiled/ua-parser-js/ua-parser.js:10:16885
    at node_modules/next/dist/server/web/spec-extension/user-agent.js:8:41
    at node_modules/next/server.js:6:0
    at middleware.js:4:17
    at middleware:middleware.js:1:17
```
I only replaced hardcoded domain from this repository by the domain part of the current hostname, which seems a lot more convenient when you deal with local / dev / staging / prod domain name.

**Everything is working perfectly fine in my local env (docker container).**

Any help is welcome, thanks 🙏

**Comment by smaeda-ks** [comment]
Hi @Sense, by the way, what is your current framework preset setting under your project settings?
If not set to Next.js, could you update that to Next.js and try it again?

**Comment by Sense** [comment]
Thanks @smaeda-ks it solved the issue it was set to `Other`
