### ISSUE TITLE
Build fails due to incompatible npm packages with React 18 (`next-mdx-remote`)

### ISSUE THREAD

**Issue by dedicatedcloud** [vercel/platforms#167]
I'm trying to deploy this to Vercel, and it keeps failing when it gets to NPM build

[07:35:06.182] Previous build cache not available
[07:35:07.389] Cloning completed: 1.365s
[07:35:07.667] Running "vercel build"
[07:35:08.354] Vercel CLI 28.4.17
[07:35:08.802] Warning: Detected "engines": { "node": ">=14.0.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[07:35:08.820] Installing dependencies...
[07:35:10.147] npm ERR! code ERESOLVE
[07:35:10.151] npm ERR! ERESOLVE could not resolve
[07:35:10.151] npm ERR! 
[07:35:10.151] npm ERR! While resolving: next-mdx-remote@3.0.8
[07:35:10.151] npm ERR! Found: react@18.2.0
[07:35:10.152] npm ERR! node_modules/react
[07:35:10.152] npm ERR!   react@"^18.2.0" from the root project
[07:35:10.152] npm ERR!   peer react@"^16 || ^17 || ^18" from @headlessui/react@1.4.3
[07:35:10.152] npm ERR!   node_modules/@headlessui/react
[07:35:10.152] npm ERR!     @headlessui/react@"^1.4.3" from the root project
[07:35:10.152] npm ERR!   12 more (@vercel/analytics, next, next-auth, react-dom, ...)
[07:35:10.152] npm ERR! 
[07:35:10.153] npm ERR! Could not resolve dependency:
[07:35:10.153] npm ERR! peer react@">=16.x <=17.x" from next-mdx-remote@3.0.8
[07:35:10.153] npm ERR! node_modules/next-mdx-remote
[07:35:10.156] npm ERR!   next-mdx-remote@"^3.0.8" from the root project
[07:35:10.156] npm ERR! 
[07:35:10.156] npm ERR! Conflicting peer dependency: react@17.0.2
[07:35:10.156] npm ERR! node_modules/react
[07:35:10.157] npm ERR!   peer react@">=16.x <=17.x" from next-mdx-remote@3.0.8
[07:35:10.157] npm ERR!   node_modules/next-mdx-remote
[07:35:10.157] npm ERR!     next-mdx-remote@"^3.0.8" from the root project
[07:35:10.157] npm ERR! 
[07:35:10.157] npm ERR! Fix the upstream dependency conflict, or retry
[07:35:10.157] npm ERR! this command with --force, or --legacy-peer-deps
[07:35:10.157] npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
[07:35:10.158] npm ERR! 
[07:35:10.158] npm ERR! See /vercel/.npm/eresolve-report.txt for a full report.
[07:35:10.158] 
[07:35:10.158] npm ERR! A complete log of this run can be found in:
[07:35:10.158] npm ERR!     /vercel/.npm/_logs/2022-11-16T07_35_09_253Z-debug-0.log
[07:35:10.170] Warning: Retrying "Install Command" with `--legacy-peer-deps` which may accept a potentially broken dependency and slow install time.
[07:35:41.225] 
[07:35:41.225] > postinstall
[07:35:41.225] > prisma generate || true
[07:35:41.226] 
[07:35:42.779] Prisma schema loaded from prisma/schema.prisma
[07:35:44.509] 
[07:35:44.510] ✔ Generated Prisma Client (3.8.1 | library) to ./node_modules/@prisma/client in 213ms
[07:35:44.510] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[07:35:44.510] ```
[07:35:44.510] import { PrismaClient } from '@prisma/client'
[07:35:44.510] const prisma = new PrismaClient()
[07:35:44.510] ```
[07:35:44.615] 
[07:35:44.616] added 622 packages in 34s
[07:35:44.616] 
[07:35:44.617] 221 packages are looking for funding
[07:35:44.617]   run `npm fund` for details
[07:35:44.643] Detected Next.js version: 13.0.2
[07:35:44.651] Detected `package-lock.json` generated by npm 7+...
[07:35:44.651] Running "npm run build"
[07:35:45.066] 
[07:35:45.066] > prebuild
[07:35:45.066] > prisma generate
[07:35:45.066] 
[07:35:46.616] Prisma schema loaded from prisma/schema.prisma
[07:35:48.383] 
[07:35:48.384] ✔ Generated Prisma Client (3.8.1 | library) to ./node_modules/@prisma/client in 236ms
[07:35:48.384] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[07:35:48.384] ```
[07:35:48.384] import { PrismaClient } from '@prisma/client'
[07:35:48.384] const prisma = new PrismaClient()
[07:35:48.384] ```
[07:35:48.534] ┌─────────────────────────────────────────────────────────┐
[07:35:48.535] │  Update available 3.8.1 -> 4.6.1                        │
[07:35:48.536] │                                                         │
[07:35:48.536] │  This is a major update - please follow the guide at    │
[07:35:48.536] │  https://pris.ly/d/major-version-upgrade                │
[07:35:48.536] │                                                         │
[07:35:48.537] │  Run the following to update                            │
[07:35:48.537] │    npm i --save-dev prisma@latest                       │
[07:35:48.537] │    npm i @prisma/client@latest                          │
[07:35:48.537] └─────────────────────────────────────────────────────────┘
[07:35:48.548] 
[07:35:48.549] > build
[07:35:48.549] > next build
[07:35:48.549] 
[07:35:49.116] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[07:35:49.117] This information is used to shape Next.js' roadmap and prioritize features.
[07:35:49.117] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[07:35:49.117] https://nextjs.org/telemetry
[07:35:49.117] 
[07:35:49.257] info  - Linting and checking validity of types...
[07:35:58.998] info  - Creating an optimized production build...
[07:36:27.886] info  - Compiled successfully
[07:36:27.887] info  - Collecting page data...
[07:36:28.569] Error: Cannot find module '@babel/core'
[07:36:28.570] Require stack:
[07:36:28.570] - /vercel/path0/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js
[07:36:28.570] - /vercel/path0/node_modules/@mdx-js/mdx/node_modules/remark-mdx/extract-imports-and-exports.js
[07:36:28.570] - /vercel/path0/node_modules/@mdx-js/mdx/node_modules/remark-mdx/index.js
[07:36:28.570] - /vercel/path0/node_modules/@mdx-js/mdx/index.js
[07:36:28.571] - /vercel/path0/node_modules/next-mdx-remote/dist/serialize.js
[07:36:28.571] - /vercel/path0/node_modules/next-mdx-remote/serialize.js
[07:36:28.571] - /vercel/path0/.next/server/pages/_sites/[site]/[slug].js
[07:36:28.571] - /vercel/path0/node_modules/next/dist/server/require.js
[07:36:28.571] - /vercel/path0/node_modules/next/dist/server/load-components.js
[07:36:28.572] - /vercel/path0/node_modules/next/dist/export/worker.js
[07:36:28.572] - /vercel/path0/node_modules/next/dist/build/worker.js
[07:36:28.572] - /vercel/path0/node_modules/next/dist/compiled/jest-worker/processChild.js
[07:36:28.572]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
[07:36:28.572]     at Function.mod._resolveFilename (/vercel/path0/node_modules/next/dist/build/webpack/require-hook.js:23:32)
[07:36:28.572]     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
[07:36:28.573]     at Module.require (node:internal/modules/cjs/loader:1057:19)
[07:36:28.573]     at require (node:internal/modules/cjs/helpers:103:18)
[07:36:28.573]     at Object.<anonymous> (/vercel/path0/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js:12:13)
[07:36:28.573]     at Module._compile (node:internal/modules/cjs/loader:1155:14)
[07:36:28.573]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[07:36:28.573]     at Module.load (node:internal/modules/cjs/loader:1033:32)
[07:36:28.573]     at Function.Module._load (node:internal/modules/cjs/loader:868:12) {
[07:36:28.574]   code: 'MODULE_NOT_FOUND',
[07:36:28.574]   requireStack: [
[07:36:28.574]     '/vercel/path0/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js',
[07:36:28.574]     '/vercel/path0/node_modules/@mdx-js/mdx/node_modules/remark-mdx/extract-imports-and-exports.js',
[07:36:28.576]     '/vercel/path0/node_modules/@mdx-js/mdx/node_modules/remark-mdx/index.js',
[07:36:28.576]     '/vercel/path0/node_modules/@mdx-js/mdx/index.js',
[07:36:28.576]     '/vercel/path0/node_modules/next-mdx-remote/dist/serialize.js',
[07:36:28.576]     '/vercel/path0/node_modules/next-mdx-remote/serialize.js',
[07:36:28.576]     '/vercel/path0/.next/server/pages/_sites/[site]/[slug].js',
[07:36:28.577]     '/vercel/path0/node_modules/next/dist/server/require.js',
[07:36:28.577]     '/vercel/path0/node_modules/next/dist/server/load-components.js',
[07:36:28.577]     '/vercel/path0/node_modules/next/dist/export/worker.js',
[07:36:28.577]     '/vercel/path0/node_modules/next/dist/build/worker.js',
[07:36:28.577]     '/vercel/path0/node_modules/next/dist/compiled/jest-worker/processChild.js'
[07:36:28.577]   ]
[07:36:28.578] }
[07:36:28.578] 
[07:36:28.578] > Build error occurred
[07:36:28.582] Error: Failed to collect page data for /_sites/[site]/[slug]
[07:36:28.582]     at /vercel/path0/node_modules/next/dist/build/utils.js:955:15 {
[07:36:28.582]   type: 'Error'
[07:36:28.582] }
[07:36:28.645] Error: Command "npm run build" exited with 1`

any help with this?

**Comment by PandiyanCool** [comment]
Facing similar issue during deployment.

**Comment by steven-tey** [comment]
Ahhh sorry about this folks @dedicatedcloud @PandiyanCool – it's because some of the packages (e.g. `next-mdx-remote`) are not compatible with React 18 <picture data-single-emoji=":sad_praying_cowboy:" title=":sad_praying_cowboy:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..6SL0cWalRarLyJ2s.ukEcWCwoDRWG8h4OeoT_8dtyoNperJ4d3G3I0zKLO519tQXPooBvhJbzsJOBOtLYuhGNHvaOo0LINsGb0xCgANam4EjJ7TSc39mXqKRWMgMevwuBCJjndcdRXa9pOnHsAtyU.UmeKI0lcl8KAuzJ9BVbrDw" alt=":sad_praying_cowboy:" align="absmiddle"></picture> 

You'll need to override the default install command with the following:

`npm install --force`

![CleanShot 2022-11-18 at 16 25 57](https://user-images.githubusercontent.com/28986134/202813462-fbcf8d20-da01-4cde-9812-5761ea4bb4b7.png)

**Comment by dedicatedcloud** [comment]
Hey thanks for getting back. I tried to override with force, and it still failed. I tried it a few times, and it fails on the NPM run build, errors different each time. I followed the guide to the letter as well, as I am a new to this . I will put 2 of the build fail logs below.

`[02:40:18.831] Cloning github.com/dedicatedcloud/tenancy-site (Branch: main, Commit: 8125c63)
[02:40:18.968] Previous build cache not available
[02:40:19.846] Cloning completed: 1.015s
[02:40:20.131] Running "vercel build"
[02:40:20.781] Vercel CLI 28.5.5
[02:40:21.208] Warning: Detected "engines": { "node": ">=14.0.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[02:40:21.218] Running "install" command: `npm install --force`...
[02:40:21.625] npm WARN using --force Recommended protections disabled.
[02:40:53.367] 
[02:40:53.368] > postinstall
[02:40:53.368] > prisma generate || true
[02:40:53.368] 
[02:40:54.862] Prisma schema loaded from prisma/schema.prisma
[02:40:56.220] 
[02:40:56.220] ✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 183ms
[02:40:56.220] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[02:40:56.221] ```
[02:40:56.221] import { PrismaClient } from '@prisma/client'
[02:40:56.221] const prisma = new PrismaClient()
[02:40:56.221] ```
[02:40:56.280] 
[02:40:56.280] added 489 packages, and audited 490 packages in 35s
[02:40:56.280] 
[02:40:56.280] 193 packages are looking for funding
[02:40:56.280]   run `npm fund` for details
[02:40:56.283] 
[02:40:56.283] found 0 vulnerabilities
[02:40:56.317] Detected Next.js version: 13.0.4
[02:40:56.324] Detected `package-lock.json` generated by npm 7+...
[02:40:56.324] Running "npm run build"
[02:40:56.735] 
[02:40:56.735] > prebuild
[02:40:56.735] > prisma generate
[02:40:56.736] 
[02:40:58.205] Prisma schema loaded from prisma/schema.prisma
[02:40:59.615] 
[02:40:59.615] ✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 228ms
[02:40:59.615] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[02:40:59.615] ```
[02:40:59.616] import { PrismaClient } from '@prisma/client'
[02:40:59.616] const prisma = new PrismaClient()
[02:40:59.616] ```
[02:41:03.608] 
[02:41:03.608] > build
[02:41:03.609] > next build
[02:41:03.609] 
[02:41:04.131] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[02:41:04.132] This information is used to shape Next.js' roadmap and prioritize features.
[02:41:04.132] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[02:41:04.132] https://nextjs.org/telemetry
[02:41:04.132] 
[02:41:04.295] info  - Linting and checking validity of types...
[02:41:12.406] Failed to compile.
[02:41:12.406] 
[02:41:12.407] ./pages/_sites/[site]/[slug].tsx:130:40
[02:41:12.407] Type error: Type '{ a: (options: { href: string; } & { children?: ReactNode; }) => JSX.Element; BlurImage: (props: BlurImageProps) => JSX.Element; Examples: ({ data }: ExamplesProps) => JSX.Element; Tweet: ({ id, metadata, className }: TweetProps) => JSX.Element; }' is not assignable to type 'MDXComponents'.
[02:41:12.407]   Type '{ a: (options: { href: string; } & { children?: ReactNode; }) => JSX.Element; BlurImage: (props: BlurImageProps) => JSX.Element; Examples: ({ data }: ExamplesProps) => JSX.Element; Tweet: ({ id, metadata, className }: TweetProps) => JSX.Element; }' is not assignable to type '{ a?: keyof IntrinsicElements | Component<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>> | undefined; ... 173 more ...; view?: keyof IntrinsicElements | ... 1 more ... | undefined; }'.
[02:41:12.407]     Types of property 'a' are incompatible.
[02:41:12.408]       Type '(options: { href: string; } & { children?: ReactNode; }) => Element' is not assignable to type 'keyof IntrinsicElements | Component<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>> | undefined'.
[02:41:12.409]         Type '(options: { href: string; } & { children?: ReactNode; }) => Element' is not assignable to type 'FunctionComponent<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>>'.
[02:41:12.409]           Types of parameters 'options' and 'props' are incompatible.
[02:41:12.409]             Type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>' is not assignable to type '{ href: string; } & { children?: ReactNode; }'.
[02:41:12.409]               Type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>' is not assignable to type '{ href: string; }'.
[02:41:12.410]                 Types of property 'href' are incompatible.
[02:41:12.410]                   Type 'string | undefined' is not assignable to type 'string'.
[02:41:12.410]                     Type 'undefined' is not assignable to type 'string'.
[02:41:12.410] 
[02:41:12.410] [0m [90m 128 | [39m[0m
[02:41:12.411] [0m [90m 129 | [39m      [33m<[39m[33marticle[39m className[33m=[39m[32m"w-11/12 sm:w-3/4 m-auto prose prose-md sm:prose-lg"[39m[33m>[39m[0m
[02:41:12.411] [0m[31m[1m>[22m[39m[90m 130 | [39m        [33m<[39m[33mMDXRemote[39m {[33m...[39mdata[33m.[39mmdxSource} components[33m=[39m{components} [33m/[39m[33m>[39m[0m
[02:41:12.411] [0m [90m     | [39m                                       [31m[1m^[22m[39m[0m
[02:41:12.411] [0m [90m 131 | [39m      [33m<[39m[33m/[39m[33marticle[39m[33m>[39m[0m
[02:41:12.411] [0m [90m 132 | [39m[0m
[02:41:12.412] [0m [90m 133 | [39m      {adjacentPosts[33m.[39mlength [33m>[39m [35m0[39m [33m&&[39m ([0m
[02:41:12.464] Error: Command "npm run build" exited with 1`

`[02:53:14.124] Cloning github.com/dedicatedcloud/tenancy-site (Branch: main, Commit: 5e8a697)
[02:53:14.261] Previous build cache not available
[02:53:16.320] Cloning completed: 2.195s
[02:53:16.561] Running "vercel build"
[02:53:17.208] Vercel CLI 28.5.5
[02:53:17.685] Warning: Detected "engines": { "node": ">=14.0.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[02:53:17.694] Running "install" command: `npm install --force`...
[02:53:18.089] npm WARN using --force Recommended protections disabled.
[02:53:48.870] 
[02:53:48.870] > postinstall
[02:53:48.870] > prisma generate || true
[02:53:48.871] 
[02:53:50.358] Prisma schema loaded from prisma/schema.prisma
[02:53:51.713] 
[02:53:51.714] ✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 178ms
[02:53:51.714] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[02:53:51.714] ```
[02:53:51.714] import { PrismaClient } from '@prisma/client'
[02:53:51.714] const prisma = new PrismaClient()
[02:53:51.714] ```
[02:53:51.771] 
[02:53:51.772] added 489 packages, and audited 490 packages in 34s
[02:53:51.772] 
[02:53:51.772] 193 packages are looking for funding
[02:53:51.772]   run `npm fund` for details
[02:53:51.774] 
[02:53:51.774] found 0 vulnerabilities
[02:53:51.801] Detected Next.js version: 13.0.4
[02:53:51.809] Detected `package-lock.json` generated by npm 7+...
[02:53:51.810] Running "npm run build"
[02:53:52.224] 
[02:53:52.224] > prebuild
[02:53:52.225] > prisma generate
[02:53:52.225] 
[02:53:53.704] Prisma schema loaded from prisma/schema.prisma
[02:53:55.082] 
[02:53:55.082] ✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 190ms
[02:53:55.082] You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[02:53:55.082] ```
[02:53:55.083] import { PrismaClient } from '@prisma/client'
[02:53:55.083] const prisma = new PrismaClient()
[02:53:55.083] ```
[02:53:55.195] 
[02:53:55.196] > build
[02:53:55.196] > next build
[02:53:55.196] 
[02:53:55.732] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[02:53:55.732] This information is used to shape Next.js' roadmap and prioritize features.
[02:53:55.733] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[02:53:55.733] https://nextjs.org/telemetry
[02:53:55.733] 
[02:53:55.894] info  - Linting and checking validity of types...
[02:54:03.920] info  - Creating an optimized production build...
[02:54:23.485] <w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/vercel/path0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!/vercel/path0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!/vercel/path0/styles/globals.css': No serializer registered for Warning
[02:54:23.485] <w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 3 items } -> webpack/lib/ModuleWarning -> Warning
[02:54:23.746] warn  - Compiled with warnings
[02:54:23.746] 
[02:54:23.747] ./styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./styles/globals.css
[02:54:23.747] Warning
[02:54:23.747] 
[02:54:23.748] (3:1) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
[02:54:23.748] 
[02:54:23.748] Import trace for requested module:
[02:54:23.748] ./styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./styles/globals.css
[02:54:23.748] ./styles/globals.css
[02:54:23.748] 
[02:54:23.748] ./styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./styles/globals.css
[02:54:23.748] Warning
[02:54:23.748] 
[02:54:23.749] (3:1) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
[02:54:23.749] 
[02:54:23.749] Import trace for requested module:
[02:54:23.749] ./styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./styles/globals.css
[02:54:23.751] ./styles/globals.css
[02:54:23.751] 
[02:54:23.752] ./styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./styles/globals.css
[02:54:23.752] Warning
[02:54:23.752] 
[02:54:23.752] (3:1) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
[02:54:23.752] 
[02:54:23.752] Import trace for requested module:
[02:54:23.753] ./styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[9].use[2]!./styles/globals.css
[02:54:23.753] ./styles/globals.css
[02:54:23.753] 
[02:54:23.753] info  - Collecting page data...
[02:54:24.924] PrismaClientInitializationError: 
[02:54:24.925] Invalid `prisma.site.findMany()` invocation:
[02:54:24.925] 
[02:54:24.925] 
[02:54:24.925] Error querying the database: Server error: `ERROR HY000 (1105): unknown error: Code: UNAVAILABLE
[02:54:24.925] server does not allow insecure connections, client must use SSL/TLS
[02:54:24.925] '
[02:54:24.926]     at RequestHandler.handleRequestError (/vercel/path0/node_modules/@prisma/client/runtime/index.js:34316:13)
[02:54:24.926]     at RequestHandler.request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:34293:12)
[02:54:24.926]     at async PrismaClient._request (/vercel/path0/node_modules/@prisma/client/runtime/index.js:35273:16)
[02:54:24.926]     at async Promise.all (index 0)
[02:54:24.926]     at async getStaticPaths (/vercel/path0/.next/server/pages/_sites/[site].js:163:41)
[02:54:24.928]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:597:33)
[02:54:24.928]     at async /vercel/path0/node_modules/next/dist/build/utils.js:929:115
[02:54:24.928]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
[02:54:24.928]   clientVersion: '4.6.1',
[02:54:24.928]   errorCode: undefined
[02:54:24.928] }
[02:54:24.930] 
[02:54:24.930] > Build error occurred
[02:54:24.935] Error: Failed to collect page data for /_sites/[site]
[02:54:24.935]     at /vercel/path0/node_modules/next/dist/build/utils.js:959:15 {
[02:54:24.936]   type: 'Error'
[02:54:24.936] }
[02:54:24.991] Error: Command "npm run build" exited with 1`

Hope this helps

**Comment by PandiyanCool** [comment]
OK, I tried force install and legacy peer installs already.
I'm having working code base with following package.json.

`{
  "private": true,
  "scripts": {
    "build": "next build",
    "dev": "next dev",
    "format:write": "prettier --write \"**/*.{css,js,json,jsx,ts,tsx}\"",
    "format": "prettier \"**/*.{css,js,json,jsx,ts,tsx}\"",
    "lint": "next lint",
    "prebuild": "prisma generate",
    "predev": "prisma generate",
    "prisma:migrate": "prisma migrate deploy",
    "start": "next start",
    "type-check": "tsc"
  },
  "engines": {
    "node": ">=14.0.0"
  },
  "dependencies": {
    "@headlessui/react": "^1.4.3",
    "@next-auth/prisma-adapter": "^1.0.1",
    "@prisma/client": "^3.8.1",
    "@vercel/analytics": "^0.1.3",
    "clsx": "^1.1.1",
    "cuid": "^2.1.8",
    "date-fns": "^2.28.0",
    "fs": "^0.0.1-security",
    "gray-matter": "^4.0.3",
    "js-cookie": "^3.0.1",
    "next": "^13.0.2",
    "next-auth": "^4.10.3",
    "next-mdx-remote": "^4.2.0",
    "next-plausible": "^3.1.4",
    "react": "^18.2.0",
    "react-confetti": "^6.0.1",
    "react-dom": "^18.2.0",
    "react-hot-toast": "^2.2.0",
    "react-textarea-autosize": "^8.3.3",
    "remark": "^14.0.2",
    "remark-mdx": "^2.0.0-rc.2",
    "sharp": "^0.30.5",
    "sitemap": "^7.1.0",
    "swr": "^1.1.2",
    "unist-util-visit": "^4.1.1",
    "use-debounce": "^7.0.1",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@tailwindcss/forms": "^0.4.0",
    "@tailwindcss/line-clamp": "^0.3.1",
    "@tailwindcss/typography": "^0.5.0",
    "@types/js-cookie": "^3.0.1",
    "@types/node": "^17.0.10",
    "@types/react": "^17.0.40",
    "@types/react-dom": "^17.0.11",
    "autoprefixer": "^10.4.2",
    "eslint": "8.11.0",
    "eslint-config-next": "^13.0.2",
    "postcss": "^8.4.5",
    "prettier": "^2.5.1",
    "prisma": "^3.8.1",
    "tailwindcss": "^3.0.15",
    "typescript": "^4.6.2"
  }
}`

And updated usage as below in `[slug].tsx`
`<MDXRemote {...data.mdxSource} components={{components}} />`

Hope it will be helpful for others.

As @steven-tey mentioned, it is because of the version upgrade.

**Comment by steven-tey** [comment]
@PandiyanCool that fixes the type error but it won't work since it's not the right syntax: https://github.com/hashicorp/next-mdx-remote#examples

I [added](https://github.com/vercel/platforms/blob/main/pages/_sites/[site]/[slug].tsx#L130-L131) a `@ts-ignore` for now, will investigate this type error a bit more!

**Comment by PandiyanCool** [comment]
Thank you @steven-tey

**Comment by steven-tey** [comment]
This should be fixed with https://github.com/vercel/platforms/pull/169
