### ISSUE TITLE
After Trying to Open a Post, I get the 500 server error

### ISSUE THREAD

**Issue by pwnguide** [vercel/platforms#332]
Hello,
I have a site called [updates.engr.si](https://updates.engr.si).
When I click on a post, I get a 500 error and this in my Vercel logs:

```
Page changed from static to dynamic at runtime /updates.engr.si/clnhec5et0003l408rwd7t38u, reason: headers
see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error
    at staticGenerationBailout (/var/task/.next/server/chunks/6697.js:1:1638)
    at headers (/var/task/.next/server/chunks/7941.js:1:1150)
    at NotFound (/var/task/.next/server/app/[domain]/[slug]/page.js:1:5869)
    at eb (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:11120)
    at /var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:22454
    at Object.toJSON (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:26464)
    at stringify (<anonymous>)
    at eO (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:14133)
    at eI (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:14661)
    at Timeout._onTimeout (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:12095) {
  page: '/updates.engr.si/clnhec5et0003l408rwd7t38u'
}
Page changed from static to dynamic at runtime /updates.engr.si/clnhec5et0003l408rwd7t38u, reason: headers
see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error
    at staticGenerationBailout (/var/task/.next/server/chunks/6697.js:1:1638)
    at headers (/var/task/.next/server/chunks/7941.js:1:1150)
    at NotFound (/var/task/.next/server/app/[domain]/[slug]/page.js:1:5869)
    at eb (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:11120)
    at /var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:22454
    at Object.toJSON (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:26464)
    at stringify (<anonymous>)
    at eO (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:14133)
    at eI (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:14661)
    at Timeout._onTimeout (/var/task/node_modules/.pnpm/next@13.5.5-canary.0_@babel+core@7.22.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:107:12095) {
  page: '/updates.engr.si/clnhec5et0003l408rwd7t38u'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by Carduelis** [comment]
Same here...

**Comment by crypticsoft** [comment]
There's a hint in this error and I found I had to add the following to `app/[domain]/[slug]/page.tsx`:

```
// static to dynamic error: https://nextjs.org/docs/messages/app-static-to-dynamic-error
export const dynamic = 'force-static';
```

You can set it to either `force-static` or `force-dynamic`.

**Comment by johnsonchandra** [comment]
just comment the lines in app/[domain]/[slug]/page.tsx:

// feel free to remove this filter if you want to generate paths for all posts
** comment  following lines
where: {
      site: {
        subdomain: "demo",
      },
    },

**Comment by leerob** [comment]
Sounds like this is resolved but we'll be working on making this easier using partial prerendering https://twitter.com/leeerob/status/1723039087391543654
