### ISSUE TITLE
New Blog posts by user showing as error 500

### ISSUE THREAD

**Issue by masonc-dev** [vercel/platforms#340]
When a user makes a new post to there site it returns error 500 when they visit the new post. Everything else seems to work fine

**Comment by aleplusplus** [comment]
Same here!

**Comment by bradledford** [comment]
Was there any resolution to this? I get this intermittently on localhost when adding an image to new posts.

**Comment by mflisikowski** [comment]
Same here!

**Comment by steven-tey** [comment]
Can you please provide steps to reproduce this? Thank you!

**Comment by focusonyoursite** [comment]
@steven-tey I found this error in the vercel logs:

 ⨯ Page changed from static to dynamic at runtime /babble.********.com/clp5gg0v20003jk08hb1tanco, reason: headers
see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error
    at l (/var/task/.next/server/chunks/441.js:7:10073)
    at d (/var/task/.next/server/chunks/753.js:1:1093)
    at c (/var/task/.next/server/app/[domain]/[slug]/page.js:1:59254)
    at em (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128289)
    at /var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:139989
    at Object.toJSON (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143567)
    at stringify (<anonymous>)
    at eE (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131952)
    at eR (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132395)
    at Timeout._onTimeout (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129175) {
  page: '/babble.******.com/clp5gg0v20003jk08hb1tanco'
}
Page changed from static to dynamic at runtime /babble.****.com/clp5gg0v20003jk08hb1tanco, reason: headers
see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error
    at l (/var/task/.next/server/chunks/441.js:7:10073)
    at d (/var/task/.next/server/chunks/753.js:1:1093)
    at c (/var/task/.next/server/app/[domain]/[slug]/page.js:1:59254)
    at em (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128289)
    at /var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:139989
    at Object.toJSON (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143567)
    at stringify (<anonymous>)
    at eE (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131952)
    at eR (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132395)
    at Timeout._onTimeout (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129175) {
  page: '/babble.******.com/clp5gg0v20003jk08hb1tanco'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by rqdewise** [comment]
This also happened and still my problem. 

Opening a post in any individual site would result to internal server error 500 only happens in production only. While, build error show "Error occurred prerendering page "./page".

**Comment by wangqiaobook** [comment]
Has anyone solved this problem?

**Comment by wangqiaobook** [comment]
> When a user makes a new post to there site it returns error 500 when they visit the new post. Everything else seems to work fine

In this project, at the following address: `/app/[domain]/[slug]/page.tsx`
There is a function named `generateStaticParams` in this file responsible for generating static pages. However, in the original code, there is a limitation that restricts the data retrieval to only subdomains with the name "demo" for generating static pages. As a result, static pages cannot be generated for subdomains created by users.

The solution is straightforward: remove or comment out the code segment responsible for this limitation.
<img width="796" alt="截屏2023-11-26 23 19 05" src="https://github.com/vercel/platforms/assets/129082483/7ecace48-e03b-4218-8f9f-04a9149faf00">

**Comment by rqdewise** [comment]
@wangqiaobook 
Yes, I have done this part. In dev mode static pages are generated smoothly but in production generating static pages always result in error.

**Comment by justanexperiment** [comment]
@wangqiaobook thank you!! this saved me hours

**Comment by mworks-proj** [comment]
I've tried commenting out this snippet of code in both sections, however, with no luck. Production is still rendering 500 internal server error on clicking any site link/ stories. Can you share your complete file (use default domain name)?

**Comment by ar-to** [comment]
what @wangqiaobook suggested indeed does the trick. The weird part is why did it not apply locally since i did not create any sites with "demo" in them and they would still get fetched normally. Took a look at https://nextjs.org/docs/app/api-reference/functions/generate-static-params#static-rendering but nothing obvious jumps out. Also I had to remove that `where` from both 
- `/app/[domain]/page.tsx`
- `/app/[domain]/[slug]/page.tsx`
As it was causing sites pages to not show posts. 

<img width="333" alt="Screenshot 2024-11-17 at 7 14 06 PM" src="https://github.com/user-attachments/assets/63d70718-d92e-4d9d-aef0-fff92403e3d7">

Just to be sure I queried the database directly using that same query used in those pages and got expected data results. 
```sql
select "posts"."slug", "posts"."siteId", "posts"."title", "posts"."createdAt", "posts"."description", "posts"."image", "posts"."imageBlurhash" 
from "posts" 
left join "sites" on "sites"."id" = "posts"."siteId" 
where sites.subdomain = 'demo'
```
<img width="1090" alt="Screenshot 2024-11-17 at 7 19 48 PM" src="https://github.com/user-attachments/assets/17376204-8d6e-431d-8a58-4a6283385437">

My best guess is some trickery with `generateStaticParams` causing some odd behavior and I lack enough understanding of it to fully debug. Hopefully my fix sticks until I break something else.

**Comment by leerob** [comment]
👋 We've updated this repo to have a more simplified example + a new guide: 

- https://github.com/vercel/platforms/pull/451
- https://vercel.com/guides/nextjs-multi-tenant-application
