### ISSUE TITLE
platform start kit - Page changed from static to dynamic at runtime when opening posts

### ISSUE THREAD

**Issue by bmnidhin** [vercel/platforms#443]
``` js
⨯ Page changed from static to dynamic at runtime /test.bmnidh.in/sbon3afxxmofvd5dii3oz3ev, reason: headers
see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error
    at l (/var/task/.next/server/chunks/573.js:7:10072)
    at d (/var/task/.next/server/chunks/884.js:1:1155)
    at u (/var/task/.next/server/app/[domain]/[slug]/page.js:1:29385)
    at em (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128289)
    at /var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:139989
    at Object.toJSON (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143567)
    at stringify (<anonymous>)
    at eE (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131952)
    at eR (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132395)
    at Timeout._onTimeout (/var/task/node_modules/.pnpm/next@14.0.2_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129175) {
  page: '/test.bmnidh.in/sbon3afxxmofvd5dii3oz3ev'
}
```

<img width="1479" alt="Screenshot 2024-12-21 at 3 47 01 PM" src="https://github.com/user-attachments/assets/1c4336e9-5c6f-4941-be42-2cd0b8eb25f5" />

**Comment by tonidy** [comment]
I encountered this issue as well. Were you able to resolve it, @bmnidhin?

**Comment by tonidy** [comment]
I came across this issue: https://github.com/vercel/platforms/issues/416. It seems there’s a working solution provided there.

**Comment by bmnidhin** [comment]
@tonidy I used the exact same fix as #416.

**Comment by leerob** [comment]
👋 We've updated this repo to have a more simplified example + a new guide: 

- https://github.com/vercel/platforms/pull/451
- https://vercel.com/guides/nextjs-multi-tenant-application
